Sprint_2
AlexanderSharygin/qa_java pull request #1
Opened 2021-11-26 14:30 UTC by AlexanderSharygin

2021-11-28 17:44 UTC, NickFlexer commented on src/test/java/com/example/AnimalExceptionTest.java
> +public class AnimalExceptionTest {
junit имеет специальный инструментарий для тестов, в которых должны выбрасываться исключения. В этом месте, как и во всех твоих тестовых классах с названиями ...ExceptionTest нужно использовать его

2021-11-28 17:46 UTC, NickFlexer commented on src/main/java/com/example/Lion.java
>          }
В тексте Exception орфографическая ошибка

Так же,  обрати внимание - лучше создавать кастомное исключение, которое уже своим названием описывает суть ошибки.

Например, в данном случае - InvalidSexName вполне бы подошло)

2021-11-28 17:50 UTC, NickFlexer requested changes
Добрый день!

В файл .gitignore стоит добавить папку target, чтобы уменьшить количество отслеживаемых файлов. Но, при этом, необходимо оставить в отслеживаемых папку target/site. Посмотри, как это можно сделать

В остальном работа выполнена хорошо, осталось разобраться только с несколькими замечаниями

2021-11-29 14:55 UTC, AlexanderSharygin commented on src/main/java/com/example/Lion.java
>          }
Fixed. Исправил орфографическую ошибку. 
В качестве примера (для тренировки) создал кастомное исключение в классе Lion

2021-11-29 14:56 UTC, AlexanderSharygin commented on src/test/java/com/example/AnimalExceptionTest.java
> +public class AnimalExceptionTest {
Fixed. Использовал подход @Rule

2021-12-01 12:52 UTC, NickFlexer commented on src/main/java/com/example/Lion.java
>          }
Отлично!

2021-12-01 12:53 UTC, NickFlexer approved these changes
Добрый день!

У меня больше замечаний нет - работа зачтена

2022-01-29 15:03 UTC, merged